name: Jest Tests

# Mainly copied from Gutenberg GitHub actions
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test-js:
    name: JavaScript
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - name: Npm install and build
      run: |
        composer install
        npm ci
        npm run build
    - name: Running the Jest tests
      run: npm run test:js -- --ci --maxWorkers=2
